# Generated by Django 4.1.2 on 2022-10-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
